// Computer_System_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 17.0 602

`timescale 1 ps / 1 ps
module Computer_System_mm_interconnect_0 (
		input  wire        VGA_clk_vga_clk_clk,                                            //                                      VGA_clk_vga_clk.clk
		input  wire        video_pixel_buffer_dma_0_reset_reset_bridge_in_reset_reset,     // video_pixel_buffer_dma_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_address,       //     video_pixel_buffer_dma_0_avalon_pixel_dma_master.address
		output wire        video_pixel_buffer_dma_0_avalon_pixel_dma_master_waitrequest,   //                                                     .waitrequest
		input  wire        video_pixel_buffer_dma_0_avalon_pixel_dma_master_read,          //                                                     .read
		output wire [31:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_readdata,      //                                                     .readdata
		output wire        video_pixel_buffer_dma_0_avalon_pixel_dma_master_readdatavalid, //                                                     .readdatavalid
		input  wire        video_pixel_buffer_dma_0_avalon_pixel_dma_master_lock,          //                                                     .lock
		output wire        video_rgb_resampler_0_avalon_rgb_slave_read,                    //               video_rgb_resampler_0_avalon_rgb_slave.read
		input  wire [31:0] video_rgb_resampler_0_avalon_rgb_slave_readdata                 //                                                     .readdata
	);

	wire         video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_waitrequest;   // video_rgb_resampler_0_avalon_rgb_slave_translator:uav_waitrequest -> video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_waitrequest
	wire  [31:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdata;      // video_rgb_resampler_0_avalon_rgb_slave_translator:uav_readdata -> video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_readdata
	wire         video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_debugaccess;   // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_debugaccess -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_debugaccess
	wire  [31:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_address;       // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_address -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_address
	wire         video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_read;          // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_read -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_read
	wire   [3:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_byteenable;    // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_byteenable -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_byteenable
	wire         video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid; // video_rgb_resampler_0_avalon_rgb_slave_translator:uav_readdatavalid -> video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_readdatavalid
	wire         video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_lock;          // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_lock -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_lock
	wire         video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_write;         // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_write -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_write
	wire  [31:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_writedata;     // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_writedata -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_writedata
	wire   [2:0] video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_burstcount;    // video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator:uav_burstcount -> video_rgb_resampler_0_avalon_rgb_slave_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator (
		.clk                    (VGA_clk_vga_clk_clk),                                                                                 //                       clk.clk
		.reset                  (video_pixel_buffer_dma_0_reset_reset_bridge_in_reset_reset),                                          //                     reset.reset
		.uav_address            (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (video_pixel_buffer_dma_0_avalon_pixel_dma_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (video_pixel_buffer_dma_0_avalon_pixel_dma_master_waitrequest),                                        //                          .waitrequest
		.av_read                (video_pixel_buffer_dma_0_avalon_pixel_dma_master_read),                                               //                          .read
		.av_readdata            (video_pixel_buffer_dma_0_avalon_pixel_dma_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (video_pixel_buffer_dma_0_avalon_pixel_dma_master_readdatavalid),                                      //                          .readdatavalid
		.av_lock                (video_pixel_buffer_dma_0_avalon_pixel_dma_master_lock),                                               //                          .lock
		.av_burstcount          (1'b1),                                                                                                //               (terminated)
		.av_byteenable          (4'b1111),                                                                                             //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                                                //               (terminated)
		.av_begintransfer       (1'b0),                                                                                                //               (terminated)
		.av_chipselect          (1'b0),                                                                                                //               (terminated)
		.av_write               (1'b0),                                                                                                //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                                                //               (terminated)
		.av_debugaccess         (1'b0),                                                                                                //               (terminated)
		.uav_clken              (),                                                                                                    //               (terminated)
		.av_clken               (1'b1),                                                                                                //               (terminated)
		.uav_response           (2'b00),                                                                                               //               (terminated)
		.av_response            (),                                                                                                    //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                                                //               (terminated)
		.av_writeresponsevalid  ()                                                                                                     //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) video_rgb_resampler_0_avalon_rgb_slave_translator (
		.clk                    (VGA_clk_vga_clk_clk),                                                                                 //                      clk.clk
		.reset                  (video_pixel_buffer_dma_0_reset_reset_bridge_in_reset_reset),                                          //                    reset.reset
		.uav_address            (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (video_pixel_buffer_dma_0_avalon_pixel_dma_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_read                (video_rgb_resampler_0_avalon_rgb_slave_read),                                                         //      avalon_anti_slave_0.read
		.av_readdata            (video_rgb_resampler_0_avalon_rgb_slave_readdata),                                                     //                         .readdata
		.av_address             (),                                                                                                    //              (terminated)
		.av_write               (),                                                                                                    //              (terminated)
		.av_writedata           (),                                                                                                    //              (terminated)
		.av_begintransfer       (),                                                                                                    //              (terminated)
		.av_beginbursttransfer  (),                                                                                                    //              (terminated)
		.av_burstcount          (),                                                                                                    //              (terminated)
		.av_byteenable          (),                                                                                                    //              (terminated)
		.av_readdatavalid       (1'b0),                                                                                                //              (terminated)
		.av_waitrequest         (1'b0),                                                                                                //              (terminated)
		.av_writebyteenable     (),                                                                                                    //              (terminated)
		.av_lock                (),                                                                                                    //              (terminated)
		.av_chipselect          (),                                                                                                    //              (terminated)
		.av_clken               (),                                                                                                    //              (terminated)
		.uav_clken              (1'b0),                                                                                                //              (terminated)
		.av_debugaccess         (),                                                                                                    //              (terminated)
		.av_outputenable        (),                                                                                                    //              (terminated)
		.uav_response           (),                                                                                                    //              (terminated)
		.av_response            (2'b00),                                                                                               //              (terminated)
		.uav_writeresponsevalid (),                                                                                                    //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                                                 //              (terminated)
	);

endmodule
