transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlib Computer_System
vmap Computer_System Computer_System
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_reset_controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_reset_synchronizer.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_006.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_001.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_customins_master_translator.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_servo_1.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_csr.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_clk_cnt.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_condt_det.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_condt_gen.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_fifo.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_mstfsm.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_rxshifter.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_txshifter.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_spksupp.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_i2c_txout.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_System_PLL.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_up_avalon_reset_from_locked_signal.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_up_altpll.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_SysID.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Slider_Switches.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_SDRAM.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Pushbuttons.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Onchip_SRAM.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/fpoint_wrapper.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/fpoint_hw_qsys.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2_cpu.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2_cpu_debug_slave_sysclk.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2_cpu_debug_slave_tck.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2_cpu_debug_slave_wrapper.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2_cpu_test_bench.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_LEDs.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_JoyStick_ADC.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_sample_store.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_sample_store_ram.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_sequencer.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_sequencer_csr.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_sequencer_ctrl.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_control.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_control_avrg_fifo.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_modular_adc_control_fsm.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/chsel_code_converter_sw_to_hw.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/fiftyfivenm_adcblock_primitive_wrapper.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/fiftyfivenm_adcblock_top_wrapper.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_JTAG_to_FPGA_Bridge.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_packets_to_master.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_packets_to_bytes.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_bytes_to_packets.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_jtag_interface.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_jtag_dc_streaming.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_jtag_sld_node.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_jtag_streaming.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_idle_remover.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_idle_inserter.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_JTAG_UART.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Interval_Timer.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_HEX5_HEX4.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_HEX3_HEX0.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Expansion_JP1.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Arduino_Reset_N.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Arduino_GPIO.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_up_accelerometer_spi_serial_bus_controller.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_up_accelerometer_spi_slow_clock_generator.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_up_accelerometer_spi_auto_init.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_up_accelerometer_spi_auto_init_ctrl.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Accelerometer_SPI.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_ADC_PLL.v}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_irq_mapper.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_006_error_adapter_0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_001_error_adapter_0.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_avalon_st_adapter_error_adapter_0.sv}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_handshake_clock_crosser.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_clock_crosser.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_st_pipeline_base.v}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_std_synchronizer_nocut.v}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_width_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_uncompressor.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_mux_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_arbitrator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_mux_001.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux_022.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux_020.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_rsp_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux_022.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux_006.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_mux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_demux_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_demux_001.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_cmd_demux.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_burst_adapter_uncmpr.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_traffic_limiter.sv}
vlog -vlog01compat -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_avalon_sc_fifo.v}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_025.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_009.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_007.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_004.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_003.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_002.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router_001.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_mm_interconnect_0_router.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_slave_agent.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_master_agent.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_slave_translator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_merlin_master_translator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/altera_customins_slave_translator.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_Nios2_custom_instruction_master_multi_xconnect.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_JTAG_to_FPGA_Bridge_p2b_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_JTAG_to_FPGA_Bridge_b2p_adapter.sv}
vlog -sv -work Computer_System +incdir+C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/submodules/Computer_System_JTAG_to_FPGA_Bridge_timing_adt.sv}
vcom -93 -work work {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Servo.vhd}
vcom -93 -work Computer_System {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/Computer_System.vhd}
vcom -93 -work Computer_System {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/computer_system_rst_controller.vhd}
vcom -93 -work Computer_System {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/computer_system_rst_controller_001.vhd}
vcom -93 -work Computer_System {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/Computer_System/synthesis/computer_system_rst_controller_002.vhd}
vcom -93 -work work {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/DE10_Lite_Computer.vhd}
vcom -93 -work work {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/CAMERA_CLK_PSC.vhd}

vcom -93 -work work {C:/Users/schillingdl/Documents/GitHub/DE10-CE2820-SoC/verilog/CAMERA_CLK_TB.vhd}

vsim -t 1ps -L altera -L lpm -L sgate -L altera_mf -L altera_lnsim -L fiftyfivenm -L rtl_work -L work -L Computer_System -voptargs="+acc"  CAMERA_CLK_TB

add wave *
view structure
view signals
run 1 sec
